PracaDyplomowa/Client/Controllers/AdvertisementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Client.Controllers
{
    public class AdvertisementsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Manage()
        {
            return View();
        }
    }
}

PracaDyplomowa/Client/Controllers/ApplicationsController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Client.Controllers
{
    public class ApplicationsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

PracaDyplomowa/Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Client.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Profile()
        {
            return View();
        }
    }
}

PracaDyplomowa/Client/Controllers/IndexController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Client.Controllers
{
    public class IndexController : Controller
    {
        public IActionResult Logowanie()
        {
            return View();
        }

        public IActionResult Rejestracja()
        {
            return View();
        }
    }
}

PracaDyplomowa/Client/Controllers/SessionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Web.Http;
// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Client.Controllers
{

    public class SessionController : ApiController
    {
        // GET: api/values
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        // GET api/values/5
        //[HttpGet("{id}")]
        //public string Get(int id)
        //{
        //    return "value";
        //}

        // POST api/values
        [HttpPost]
        public void Post([FromBody]SessionValues values)
        {

            //if (Session.GetString("LoggedIn") != values.LoggedIn)
            //{
            //    Session.SetString("LoggedIn", values.LoggedIn);
            //}

            //if (Session.GetString("UserId") != values.UserId)
            //{
            //    Session.SetString("UserId", values.UserId);
            //}

            //if (Session.GetString("Email") != values.Email)
            //{
            //    Session.SetString("Email", values.Email);
            //}

            //return ;
        }

        // PUT api/values/5
        //[HttpPut("{id}")]
        //public void Put(int id, [FromBody]string value)
        //{
        //}

        // DELETE api/values/5
        //[HttpDelete("{id}")]
        //public void Delete(int id)
        //{
        //}
    }
}

PracaDyplomowa/Client/Views/Advertisements/Index.cshtml
@{
    ViewData["Title"] = "Advertisements";
}
@section Styles {
    <link rel="stylesheet" href="~/css/advertListPage.css" type="text/css" />
}
@section scripts
{
    <script src="~/js/advertListPage.js" asp-append-version="true"></script>
}
<div class="container">
    <h1>Advertisements</h1>
    <hr>
        <div class="row">
            <div class="list-group advertisements">
            </div>
        </div>
    </hr>
</div>

PracaDyplomowa/Client/Views/Advertisements/Manage.cshtml
@{
    ViewData["Title"] = "Advertisements management";
}
@section Styles {
    <link rel="stylesheet"  href="~/css/advertPage.css" type="text/css" />
}
@section scripts
{
    <script src="~/js/manageAdvertisements.js" asp-append-version="true"></script>
}

<div class="container">
    <h1>My advertisements</h1>
    <hr>
    <div class="row">
        <div class="list-group advertisements">
        </div>
        <button type="button" class="btn btn-default addAdvertisement">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add advertisement
        </button>
    </div>
    </hr>
</div>

PracaDyplomowa/Client/Views/Applications/Index.cshtml
@{
    ViewData["Title"] = "My Applications";
}
@section Styles {
    <link rel="stylesheet" href="~/css/myApplications.css" type="text/css" />
}
@section scripts
{
    <script src="~/js/myApplications.js" asp-append-version="true"></script>
}
<table class="table table-striped applications">
    <thead>
        <tr>
            <th style="width: 10%;">#</th>
            <th style="width: 40%">Offer title</th>
            <th style="width: 20%">Date of application</th>
            <th style="width: 20%;">Status</th>
            <th style="width: 10%;"></th>
        </tr>
    </thead>
    <tbody style="max-height: 400px;">
    </tbody>
</table>

PracaDyplomowa/Client/Views/Home/Profile.cshtml
@{
    ViewData["Title"] = "Your profile";
}
@section scripts
{
    <script src="~/js/editProfile.js" asp-append-version="true"></script>
}

<div class="container">
    <h1>Edit Profile</h1>
    <hr>
    <div class="row">
        <!-- left column -->
        <div class="col-md-5">
            <h3>Personal info</h3>
            <form class="form-horizontal profile" role="form">
                <div class="form-group text-center">
                    <label class="col-lg-3 control-label">
                        <img src="//placehold.it/100" class="avatar img-circle" alt="avatar" />
                    </label>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">First name:</label>
                    <div class="col-lg-8">
                        <input required="true" class="form-control" value="" type="text" name="Name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Surname:</label>
                    <div class="col-lg-8">
                        <input required="true" class="form-control" value="" type="text" name="Surname">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Company:</label>
                    <div class="col-lg-8">
                        <input required="true" class="form-control" value="" type="text">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Email:</label>
                    <div class="col-lg-8">
                        <input required="true" disabled class="form-control" value="" type="text" name="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label"></label>
                    <div class="col-md-8">
                        <input class="btn btn-primary" name="save" value="Save Changes" type="button">
                        <span></span>
                        <input class="btn btn-default" value="Cancel" type="reset">
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-7">
            <h3>Education</h3>
            <div class="list-group education">
            </div>
            <button type="button" class="btn btn-default addEducation">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add education
            </button>
            <h3>Work Experience</h3>
            <div class="list-group work-experience">
            </div>
            <button type="button" class="btn btn-default addExperience">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add experience
            </button>
        </div>
    </div>
</div>

PracaDyplomowa/Client/Views/Index/Logowanie.cshtml
@{
    ViewData["Title"] = "Log In";
}

@section scripts
{
    <script src="~/js/login.js" asp-append-version="true"></script>
}
<div class="login">
    <div class="container custom-container">
        <div class="va-wrapper">
            <div class="view login-view container">
                <div class="box row">
                    <div class="email-password-area col-xs-12 large col-sm-12">
                        <div class="header">
                            <span>Log In</span>
                        </div>
                        <form method="post" role="form" class="login-form form-horizontal">

                            <div class="form-group group-login">
                                <label class="col-sm-4">
                                    Login lub email
                                </label>
                                <div class="col-sm-8">
                                    <input placeholder="Email" name="email" value="" class="form-control" required="true" type="text">
                                </div>
                            </div>
                            <div class="form-group group-password">
                                <label class="col-sm-4">
                                    Hasło
                                </label>
                                <div class="col-sm-8">
                                    <input placeholder="Password" name="password" value="" class="form-control" required="true" type="password">
                                </div>
                            </div>
                            <div>
                                <button type="button" class="login btn btn-login btn-sp-green">Zaloguj</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PracaDyplomowa/Client/Views/Index/Rejestracja.cshtml
@{
    ViewData["Title"] = "Register";
}

@section scripts
{
    <script src="~/js/registration.js" asp-append-version="true"></script>
}

<div class="register">
    <div class="container custom-container">
        <div class="va-wrapper">
            <div class="view registration-view container">
                <div class="box row">
                    <div class="col-sm-12">
                        <div class="header">
                            <span>Create Account</span>
                        </div>
                        <form method="post" role="form" class="registration-form form-horizontal sp-form">
                            <div form-group="true" class="form-group group-email">
                                <label class="col-sm-4">Email</label>
                                <div class="col-sm-8">
                                    <input placeholder="Email" name="email" class="form-control" value="" required="true" type="email">
                                </div>
                            </div>
                            <div form-group="true" class="form-group group-password">
                                <label class="col-sm-4">Password</label>
                                <div class="col-sm-8">
                                    <input placeholder="Password" name="password" class="form-control" value="" required="true" type="password">
                                </div>
                            </div>
                            <button type="button" class="btn btn-register btn-sp-green">Create Account</button>
                        </form>
                    </div>
                </div>
                @Html.ActionLink("Back to Log In", "Logowanie", "Index", null, null, "", null, new { @class = "to-login" })
            </div>
        </div>
    </div>
</div>

PracaDyplomowa/Client/Views/Index/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment names="Development">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="~/css/loginPage.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("scripts", required: false)
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <ul class="nav navbar-nav">
            <li>@ViewBag.Email</li>
            <li>@Html.ActionLink("Rejestracja", "Rejestracja", "Index", null, null)</li>
            <li>@Html.ActionLink("Zaloguj", "Logowanie", "Index", null, null)</li>
        </ul>
</div>
    <div>
        @RenderBody()
    </div>
</body>
</html>

PracaDyplomowa/Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - test</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

PracaDyplomowa/Client/Views/Shared/_LayoutLoggedUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment names="Development">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("Styles", required: false)
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@

        @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>*@
        @*<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap3-dialog/dist/js/bootstrap-dialog.js"></script>
        <script src="~/lib/bootbox/bootbox.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("scripts", required: false)
    </environment>
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <ul class="nav navbar-nav navbar-left">
                <li>@Html.ActionLink("My profile", "Profile", "Home", null, null)</li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown">Advertisements<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Advertisements", "Index", "Advertisements", null, null)</li>
                        <li>@Html.ActionLink("My applications", "Index", "Applications", null, null)</li>
                        <li>@Html.ActionLink("My advertisements", "Manage", "Advertisements", null, new { @class = "manageAdvertisements" })</li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav">

                </li>
                <li>@Html.ActionLink("Log Out", "Logowanie", "Index", null, new { @class = "logoutButton" })</li>
                <li>@*@Html.ActionLink("Mój profil", "Profile", "Home", null, null)*@</li>
        </ul>
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>